name: test
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install module and dependencies
        run: python -m pip install ./
      - name: Test with pytest
        run: pytest -vv --cov-config=pyproject.toml ./test --cov=mycalc --cov-report xml:coverage.xml
      - name: Get Coverage
        uses: orgoro/coverage@v3.1
        with:
          thresholdModified: 0.5
          thresholdAll: 0.4

          thresholdNew: 0.5
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}